### PR TITLE
Additional rewrite rules for InterSystems IRIS

### PR DESCRIPTION
**Pull request by bdeboe**
This PR includes two additions to the initial dialect submission after preparation of our DataConnector PR and further review with @alex-odysseus 

* as part of verifying the dplyr unit tests in DataConnector, we found an issue with `FROM ( VALUES ... )` that is now corrected
* we identified a missing rewrite rule for `COALESCE(DATEADD())` combinations that would lead to unrecognized date formatting when running some cohorts and analyses.

### CODE REVIEW

**Comment by schuemie** [comment]
The diff of the CSV file shows all lines have changed, probably because of different end-of-line indicators (carriage return?). Could you revise the PR so the diff shows only those lines that have changed?

**Comment by bdeboe** [comment]
apologies, there seems to have been a disagreement between RStudio and VS Code, but it looks like they're now back to the expected LF line ending

**Review by schuemie — APPROVED** [review]

**Comment by bdeboe** [comment]
Hi @schuemie , 
is it possible to create a new 1.19.1 release that includes this, such that we can refer to the right version number right away when submitting our corresponding PR for the OHDSI/DatabaseConnector repo?
Many thanks!
benjamin

**Comment by schuemie** [comment]
Creating a release is unfortunately quite a labor-intensive process. I'm happy to create a new release, but then there will be no more releases for a while. Are you sure you have all changes you need for the foreseeable future?

**Comment by schuemie** [comment]
SqlRender 1.19.1 has just been released

**Pull request merged**
