### PR TITLE
Add overloaded method to support backwards compatibility

### PR DESCRIPTION
**Pull request by alexfranken**
This pull request contains an overloaded method to ensure backwards compatibility (i.e. using the default generated sessionId)

### CODE REVIEW

**Comment by alexfranken** [comment]
@schuemie - Below is the exception I get when trying the oracle branch.
```
2015-03-03 09:29:34.627 INFO taskExecutor-1 org.springframework.batch.core.launch.support.SimpleJobLauncher -  - Job: [SimpleJob: [name=OhdsiExampleJob]] completed with the following parameters: [{param=parameter with 250 char limit, time=1425392973682}] and the following status: [COMPLETED]
2015-03-03 09:36:59.031 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 0 : use OHDSI
2015-03-03 09:36:59.668 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 1 : delete from OHDSI.HERACLES_results where cohort_definition_id IN (1) and analysis_id IN (1,2,1800,1801,1802)
2015-03-03 09:36:59.956 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 2 : delete from OHDSI.HERACLES_results_dist where cohort_definition_id IN (1) and analysis_id IN (1,2,1800,1801,1802)
2015-03-03 09:37:00.897 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 3 : IF OBJECT_ID('HERACLES_cohort', 'U') IS NOT NULL --This should only do something in Oracle
  drop table HERACLES_cohort
2015-03-03 09:37:00.897 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 4 : IF OBJECT_ID('tempdb..#HERACLES_cohort', 'U') IS NOT NULL
  drop table #HERACLES_cohort
2015-03-03 09:37:00.897 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 5 : select subject_id, cohort_definition_id, cohort_start_date, cohort_end_date 
	into #HERACLES_cohort
from OHDSI.cohort
where cohort_definition_id in (1)

2015-03-03 09:37:00.898 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 6 : insert into HERACLES_results (cohort_definition_id, analysis_id, count_value)
select c1.cohort_definition_id, 1 as analysis_id,  COUNT_BIG(distinct person_id) as count_value
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
group by c1.cohort_definition_id
2015-03-03 09:37:00.898 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 7 : insert into HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
select c1.cohort_definition_id, 2 as analysis_id,  gender_concept_id as stratum_1, COUNT_BIG(distinct person_id) as count_value
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
group by c1.cohort_definition_id, GENDER_CONCEPT_ID

2015-03-03 09:37:00.898 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 8 : insert into HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
select c1.cohort_definition_id, 
	1800 as analysis_id, 
	year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH as stratum_1, 
	COUNT_BIG(p1.person_id) as count_value
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id, cohort_start_date from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
group by c1.cohort_definition_id, year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH

2015-03-03 09:37:00.898 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 9 : insert into HERACLES_results_dist (cohort_definition_id, analysis_id, count_value, min_value, max_value, avg_value, stdev_value, median_value, p10_value, p25_value, p75_value, p90_value)
select cohort_definition_id, 
	1801 as analysis_id,
	COUNT_BIG(count_value) as count_value,
	min(count_value) as min_value,
	max(count_value) as max_value,
	avg(1.0*count_value) as avg_value,
	stdev(count_value) as stdev_value,
	max(case when p1<=0.50 then count_value else -9999 end) as median_value,
	max(case when p1<=0.10 then count_value else -9999 end) as p10_value,
	max(case when p1<=0.25 then count_value else -9999 end) as p25_value,
	max(case when p1<=0.75 then count_value else -9999 end) as p75_value,
	max(case when p1<=0.90 then count_value else -9999 end) as p90_value
from
(
select c1.cohort_definition_id,
	year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH as count_value,
	1.0*(row_number() over (partition by c1.cohort_definition_id order by year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH))/(COUNT_BIG(year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH) over (partition by c1.cohort_definition_id)+1) as p1
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id, cohort_start_date from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
) t1
group by cohort_definition_id

2015-03-03 09:37:00.899 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 10 : insert into HERACLES_results_dist (cohort_definition_id, analysis_id, stratum_1, count_value, min_value, max_value, avg_value, stdev_value, median_value, p10_value, p25_value, p75_value, p90_value)
select cohort_definition_id, 
	1802 as analysis_id,
	gender_concept_id as stratum_1,
	COUNT_BIG(count_value) as count_value,
	min(count_value) as min_value,
	max(count_value) as max_value,
	avg(1.0*count_value) as avg_value,
	stdev(count_value) as stdev_value,
	max(case when p1<=0.50 then count_value else -9999 end) as median_value,
	max(case when p1<=0.10 then count_value else -9999 end) as p10_value,
	max(case when p1<=0.25 then count_value else -9999 end) as p25_value,
	max(case when p1<=0.75 then count_value else -9999 end) as p75_value,
	max(case when p1<=0.90 then count_value else -9999 end) as p90_value
from
(
select c1.cohort_definition_id,
	p1.gender_concept_id,
	year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH as count_value,
	1.0*(row_number() over (partition by p1.gender_concept_id, c1.cohort_definition_id order by year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH))/(COUNT_BIG(year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH) over (partition by p1.gender_concept_id, c1.cohort_definition_id)+1) as p1
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id, cohort_start_date from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
) t1
group by cohort_definition_id, gender_concept_id

2015-03-03 09:37:00.899 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 11 : TRUNCATE TABLE #HERACLES_cohort
2015-03-03 09:37:00.899 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 12 : DROP TABLE #HERACLES_cohort
2015-03-03 09:37:00.900 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 13 : delete from HERACLES_results where count_value <= 0
2015-03-03 09:37:00.900 DEBUG http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 14 : delete from HERACLES_results_dist where count_value <= 0
2015-03-03 09:37:00.900 INFO http-nio-8080-exec-4 org.ohdsi.webapi.service.CohortAnalysisService -  - Beginning run for cohort analysis task: 
 {"smallCellCount":0,"cohortDefinitionIds":["1"],"analysisIds":["1","2","1800","1801","1802"],"conditionConceptIds":[],"drugConceptIds":[],"procedureConceptIds":[],"observationConceptIds":[],"measurementConceptIds":[]}
2015-03-03 09:37:01.040 INFO taskExecutor-1 org.springframework.batch.core.launch.support.SimpleJobLauncher -  - Job: [SimpleJob: [name=cohortAnalysisJob]] launched with the following parameters: [{cohortDefinitionId:1=1, time=1425393420945}]
2015-03-03 09:37:01.231 INFO taskExecutor-1 org.springframework.batch.core.job.SimpleStepHandler -  - Executing step: [cohortAnalysisStep]
2015-03-03 09:37:18.037 INFO taskExecutor-1 org.springframework.beans.factory.xml.XmlBeanDefinitionReader -  - Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2015-03-03 09:37:18.104 INFO taskExecutor-1 org.springframework.jdbc.support.SQLErrorCodesFactory -  - SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2015-03-03 09:37:18.135 ERROR taskExecutor-1 org.springframework.batch.core.step.AbstractStep -  - Encountered an error executing step cohortAnalysisStep in job cohortAnalysisJob
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [use OHDSI; delete from OHDSI.HERACLES_results where cohort_definition_id IN (1) and analysis_id IN (1,2,1800,1801,1802); delete from OHDSI.HERACLES_results_dist where cohort_definition_id IN (1) and analysis_id IN (1,2,1800,1801,1802); IF OBJECT_ID('HERACLES_cohort', 'U') IS NOT NULL --This should only do something in Oracle
  drop table HERACLES_cohort; IF OBJECT_ID('tempdb..#HERACLES_cohort', 'U') IS NOT NULL
  drop table #HERACLES_cohort; select subject_id, cohort_definition_id, cohort_start_date, cohort_end_date 
	into #HERACLES_cohort
from OHDSI.cohort
where cohort_definition_id in (1)
; insert into HERACLES_results (cohort_definition_id, analysis_id, count_value)
select c1.cohort_definition_id, 1 as analysis_id,  COUNT_BIG(distinct person_id) as count_value
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
group by c1.cohort_definition_id; insert into HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
select c1.cohort_definition_id, 2 as analysis_id,  gender_concept_id as stratum_1, COUNT_BIG(distinct person_id) as count_value
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
group by c1.cohort_definition_id, GENDER_CONCEPT_ID
; insert into HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
select c1.cohort_definition_id, 
	1800 as analysis_id, 
	year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH as stratum_1, 
	COUNT_BIG(p1.person_id) as count_value
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id, cohort_start_date from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
group by c1.cohort_definition_id, year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH
; insert into HERACLES_results_dist (cohort_definition_id, analysis_id, count_value, min_value, max_value, avg_value, stdev_value, median_value, p10_value, p25_value, p75_value, p90_value)
select cohort_definition_id, 
	1801 as analysis_id,
	COUNT_BIG(count_value) as count_value,
	min(count_value) as min_value,
	max(count_value) as max_value,
	avg(1.0*count_value) as avg_value,
	stdev(count_value) as stdev_value,
	max(case when p1<=0.50 then count_value else -9999 end) as median_value,
	max(case when p1<=0.10 then count_value else -9999 end) as p10_value,
	max(case when p1<=0.25 then count_value else -9999 end) as p25_value,
	max(case when p1<=0.75 then count_value else -9999 end) as p75_value,
	max(case when p1<=0.90 then count_value else -9999 end) as p90_value
from
(
select c1.cohort_definition_id,
	year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH as count_value,
	1.0*(row_number() over (partition by c1.cohort_definition_id order by year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH))/(COUNT_BIG(year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH) over (partition by c1.cohort_definition_id)+1) as p1
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id, cohort_start_date from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
) t1
group by cohort_definition_id
; insert into HERACLES_results_dist (cohort_definition_id, analysis_id, stratum_1, count_value, min_value, max_value, avg_value, stdev_value, median_value, p10_value, p25_value, p75_value, p90_value)
select cohort_definition_id, 
	1802 as analysis_id,
	gender_concept_id as stratum_1,
	COUNT_BIG(count_value) as count_value,
	min(count_value) as min_value,
	max(count_value) as max_value,
	avg(1.0*count_value) as avg_value,
	stdev(count_value) as stdev_value,
	max(case when p1<=0.50 then count_value else -9999 end) as median_value,
	max(case when p1<=0.10 then count_value else -9999 end) as p10_value,
	max(case when p1<=0.25 then count_value else -9999 end) as p25_value,
	max(case when p1<=0.75 then count_value else -9999 end) as p75_value,
	max(case when p1<=0.90 then count_value else -9999 end) as p90_value
from
(
select c1.cohort_definition_id,
	p1.gender_concept_id,
	year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH as count_value,
	1.0*(row_number() over (partition by p1.gender_concept_id, c1.cohort_definition_id order by year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH))/(COUNT_BIG(year(c1.cohort_start_date) - p1.YEAR_OF_BIRTH) over (partition by p1.gender_concept_id, c1.cohort_definition_id)+1) as p1
from omopv5_de.dbo.PERSON p1
inner join (select subject_id, cohort_definition_id, cohort_start_date from #HERACLES_cohort) c1
on p1.person_id = c1.subject_id
) t1
group by cohort_definition_id, gender_concept_id
; TRUNCATE TABLE #HERACLES_cohort; DROP TABLE #HERACLES_cohort; delete from HERACLES_results where count_value <= 0; delete from HERACLES_results_dist where count_value <= 0]; SQL state [null]; error code [17081]; error occurred during batching: ORA-00900: invalid SQL statement
; nested exception is java.sql.BatchUpdateException: error occurred during batching: ORA-00900: invalid SQL statement

	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:416)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:611)
	at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet$1.doInTransaction(CohortAnalysisTasklet.java:40)
	at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet$1.doInTransaction(CohortAnalysisTasklet.java:1)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet.execute(CohortAnalysisTasklet.java:36)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:198)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:386)
	at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:304)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.BatchUpdateException: error occurred during batching: ORA-00900: invalid SQL statement

	at oracle.jdbc.driver.OracleStatement.executeBatch(OracleStatement.java:4586)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at org.springframework.jdbc.core.JdbcTemplate$1BatchUpdateStatementCallback.doInStatement(JdbcTemplate.java:572)
	at org.springframework.jdbc.core.JdbcTemplate$1BatchUpdateStatementCallback.doInStatement(JdbcTemplate.java:559)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:405)
	... 23 more
```

**Comment by alexfranken** [comment]
Looks like there were a couple of problems.  
1. given the new maven support, Eclipse was not copying the csv file to the target/classes.  See latest pull request to master for fix.
2. Looks like we are hoping to find a value of 'oracle\toracle' in the csv file.  I'm assuming the source needs to be 'sql server'...?

**Comment by alexfranken** [comment]
I have confirmed that the branch works as advertised using the null-specified session id.  I'll post a question on the forum topic...

**Comment by alexfranken** [comment]
Looks like there is a problem, in that the replacement of `%sessionId%` only happens once.  So, currently, either way, we get a "globalSessionId".

```
	public static String translateSql(String sql, String sourceDialect, String targetDialect, String sessionId, String pathToReplacementPatterns) {
		ensurePatternsAreLoaded(pathToReplacementPatterns);
		if (sessionId == null) {
			if (globalSessionId == null)
				globalSessionId = generateSessionId();
			sessionId = globalSessionId;
		}
		List<String[]> replacementPatterns = sourceTargetToReplacementPatterns.get(sourceDialect + "\t" + targetDialect);
		if (replacementPatterns == null)
			return sql;
		else
			return translateSql(sql, replacementPatterns, sessionId);
	}
```
Since your `sourceTargetToReplacementPatterns` above is a static member, and since the replacement modifies the actual reference `pair` below, the replacement only happens once.

```
	private static String translateSql(String sql, List<String[]> replacementPatterns, String sessionId) {
		for (String[] pair : replacementPatterns) {
			pair[1] = pair[1].replace("%session_id%", sessionId);
			List<Block> parsedPattern = parseSearchPattern(pair[0]);
			sql = searchAndReplace(sql, parsedPattern, pair[1]);
		}
		return sql;
	}
```

**Comment by schuemie** [comment]
Oops! I don't know what I was thinking...

Should now be fixed in 4458e7a434e431e49ac4ff325eb589c3c6836293.

**Comment by alexfranken** [comment]
Confirmed.

**Comment by schuemie** [comment]
@alexfranken : please note I just pushed some more changes to the sessionId behaviour (4ae3d3702e26f435eb74b43c9f937748f5612bbf). I was testing the functionality for our R packages (Achilles, CohortMethod) and was hitting to many 'id too long' errors (Oracle only allows 30 characters for a table name). I dropped the 'tmp' prefix and '_' postfix, and reduced the sessionId to 8 characters.

**Pull request merged**
