### PR TITLE
Adds Spark dialect (without updated SqlRender JAR file)

### PR DESCRIPTION
**Pull request by alondhe**
Issue #247 Add Spark dialect to develop branch.

This PR adds Apache Spark (v3.x) support to SqlRender. It has been tested with Databricks Spark v3.1.1 and has been used in our version of Atlas.

I have not included the SqlRender JAR file.

### CODE REVIEW

**Comment by schuemie** [comment]
Thanks! This looks like excellent work. 

However, I would really like to have a testing platform available for each dialect we support. What options are there to make a Spark server with some CDM data (we currently use Synpuf) available to the OHDSI community?

**Comment by alondhe** [comment]
> Thanks! This looks like excellent work.
> 
> However, I would really like to have a testing platform available for each dialect we support. What options are there to make a Spark server with some CDM data (we currently use Synpuf) available to the OHDSI community?

Hi @schuemie,

There is a community edition of Databricks we could use. I can configure it (with synpuf loaded) and send you the details, would that work?

Thanks,
Ajit

**Comment by schuemie** [comment]
What would be needed for either option? (real license or installing on an OHDSI machine)

**Comment by alondhe** [comment]
@schuemie on the first, some budget to run a small cluster. We are engaging with Databricks about this early next week. On the second, I'm trying this out on a local machine to map out the steps.

**Comment by vojtechhuser** [comment]
Any update on this. My team would need spark support as well. @schuemie @alondhe

**Comment by alondhe** [comment]
> Any update on this. My team would need spark support as well. @schuemie @alondhe

We met with Databricks, they are evaluating the idea. In the interim, I am exploring a local install of Spark to see if that can accomplish the goal of providing a test environment.

**Comment by vojtechhuser** [comment]
I understand that perhaps some test environment is in the cards. Any udpates? @schuemie

**Comment by alondhe** [comment]
We're getting close now. We have the account for this cluster, now just setting it up today with Databricks. 

@schuemie once I have this cluster, I can share the access with you. What would the next steps be to adding it to the OHDSI testing framework?

**Comment by schuemie** [comment]
Once I have them I'll add the credentials to the secret environmental variables available in our GitHub Actions, and we can add unit tests using them. To me important places to start would be [FeatureExtraction](https://github.com/OHDSI/FeatureExtraction/tree/master/tests) and [DatabaseConnector](https://github.com/OHDSI/DatabaseConnector/blob/master/tests/testthat/test-connection.R). 

For the tests we'd also need to make the Spark JDBC driver available to DatabaseConnector. Is it [this one](https://databricks.com/spark/jdbc-drivers-download)?

**Comment by alondhe** [comment]
> @alondhe -- can you manually resolve the merge-conflicts (a simple `git pull` from origin) should fix this on your end, and then re-make the `pr`?

Sure, will do once we get the cluster up. We're hoping to have it up and running Thursday.

**Comment by msuchard** [comment]
@alondhe -- make sure you are developing for `DatabaseConnector v4`.   There is no longer a `DatabaseConnectorJar` dependency (as CRAN got mad at the size).  `DC` now needs the downloads automated in `downloadJdbcDrivers()`.

**Comment by alondhe** [comment]
Update: as per usual, funding something tiny takes way longer than it should :) 

We're expecting the cluster to be available next Friday.

**Comment by alondhe** [comment]
@vojtechhuser @schuemie @msuchard we have the cluster up and running now. Closing this PR and will re-issue it to resolve the merge conflicts.

@schuemie please let me know via email what's the best approach for credential sharing.

**Pull request closed without merging**
