### PR TITLE
Added support for BigQuery standard SQL

### PR DESCRIPTION
**Pull request by pavgra**
https://cloud.google.com/bigquery/docs/reference/standard-sql/

### CODE REVIEW

**Comment by pavgra** [comment]
@schuemie ,

Regarding the `BigQueryTranslate.java`:
1) The code was not following the SqlRender pattern used for all other DBs: there is some common utility code and all DB specific rules are defined in `replacementPatterns.csv`. So the BQ handling was inconsistent with other DBs handling. Current PR implements BQ support in the same way as it is done for other DBs
2) You are very welcome to test https://github.com/OHDSI/Achilles/pull/360, https://github.com/OHDSI/WebAPI/pull/786 and make sure that all the functionality works
3) The work presented in the PR is done for Google

Are these reasons enough for you?

**Comment by schuemie** [comment]
No, those are not enough reasons for me:

1. It was not following the same pattern as the other platforms because what needed to be done didn't fit the same pattern. You say you achieved the same thing with the CSV rules, but there are [a lot of unit tests](https://github.com/OHDSI/SqlRender/blob/master/tests/testthat/test-translateSql.R#L892) that say you don't.

2. I don't have access to a Google BigQuery instance, so I'm unable to test this. But just because it works for your two use cases doesn't mean we can abandon all others.

Why can't we leave BigQueryTranslate.java as it is, and get all unit tests (old and new) to pass?

**Comment by pavgra** [comment]
@schuemie , I've reverted removal of separate BQ service and fixed tests, let me explain the changes.

1. Removal of `bigQueryReplaceStringConcatsInStatement` from `BigQueryTranslate.java`:

    The mechanism tries to replace `+` with `CONCAT` for string concatenation. Although for several cases this is being achieved, the simplest one - `string_column_a + string_column_b` is not handled for obvious reasons but required to be processed also:
    image
    We faced the same issue with Impala before and that's why all string concatenations in WebAPI and Achilles were transformed from `+` to `CONCAT()` in source statements. Therefore, I do not see a reason to leave a mechanism which neither completely working nor really required. `CONCAT` related tests were removed due to the same reason.

2. Removal of `bigQueryUnquoteIdInLists` from `BigQueryTranslate.java`:

    This function confused me a bit. Imagine the case:

    image

    The translation here doesn't make sense at all. What is more, it breaks things. Not sure why it was required and how can you change data type of parameters w/o knowledge of field's data type (I see that they tried to base logic on `_id` postfix in column but that is not solid, just look at concept table columns and their data types). The related tests were therefore dropped.

3. `select cast(x as:string)` and `select cast(x as:integer)` - where is this syntax taken from?

4. `select into` tests seems like used legacy SQL (instead of BQ Standard SQL) and the overall rule was hardcoded to the single `temp` schema. That was replaced with the same approach as used for Oracle / Impala temp schemas.

Why I removed the BQ service initially at all? - through all the contributions done by Odysseus I've observed that making things work with changing source SQL code instead of introducing new rules is preferrable by community (at least, I got such feeling). Since I was able to make all functionality of WebAPI and Achilles (which is quite representative set of SQLs) working w/o the service, I've dropped it. Less code, less bugs. But not willing to spend much time on debates - ok, here is it back with some excluions described above.

**Comment by schuemie** [comment]
Thanks @pavgra for providing a clear rationale for deleting someone else's contributions, and especially for making sure all unit tests pass. I can now accept this pull request.

I agree that it would be preferable to remove the custom code altogether. Most of the remaining code deals specifically with not being able to `GROUP BY` a derived value, which we do a lot in OHDSI code, for example:
```sql
SELECT EXTRACT(YEAR FROM observation_period_start_date) AS start_year,
   COUNT(*) AS period_count
FROM observation_period
GROUP BY EXTRACT(YEAR FROM observation_period_start_date);
```
apparently will throw an error, and needs to be rewritten to
```sql
SELECT EXTRACT(YEAR FROM observation_period_start_date) AS start_year,
   COUNT(*) AS period_count
FROM observation_period
GROUP BY 1;
```
to work. This [appears to have been true 4 years ago](https://stackoverflow.com/questions/24003380/bigquery-order-by-count), but as I mentioned, I have no BigQuery instance to test if this is still the case, and googling for it doesn't provide any details. The other code seems to deal with CTEs.

**Pull request merged**
