### PR TITLE
Fixes #260, #261, #262, adds #271

### LINKED ISSUE #260: Spark inserts with unioned selects
In Atlas, we use the sparkHandleInsert function to deal with the pesky issue of Spark not being able to run inserts with a subset of columns. 

This function is not working for Heracles reports (Cohort Reporting in Atlas) as it uses a cadence of 

```
insert into table
select stuff
union all
select morestuff
union all
select evenmorestuff
```

The sparkHandleInsert function needs logic to apply the reconstruction of all selects in the insert to match the full table structure.

### PR DESCRIPTION
**Pull request by alondhe**
Spark Fixes #260, #261, #262, adds #271

(I've not included my JAR file)

### CODE REVIEW

**Comment by schuemie** [comment]
We cannot have dialect-specific functions like `sparkHandleInsert()`. That defeats the entire purpose of SqlRender. If I understand correctly, this requirement on `INSERT` statements seems a real deal-breaker. We are not going to change all our software to accommodate it (`INSERT` statements are sprinkled throughout HADES). 

I propose taking this up with the Spark folks.

**Comment by alondhe** [comment]
Understood @schuemie , I don't like having this either. But let me clarify a bit:

We do have sparkHandleInsert() already in the SqlRender BigQuerySparkTranslate Java library, and invoke it in WebAPI when Atlas SQL executions headed for Spark are fired off. 

The R function wraps this, and then I was thinking we could mirror the pattern above in DatabaseConnector::executeSql so that INSERTs in HADES or other OHDSI R packages would go through sparkHandleInsert if the dialect is Spark. It would be a dialect specific path as you mentioned, but I think it beats trying to keep up with a moving target (rewriting all inserts to have full column lists).

I agree this is a very annoying limitation of Spark (welcome to my world ;) ) but they don't have the insert with partial column list enhancement in the roadmap yet. We're pushing for it, but no timeline. 

Could we take this approach for now, and then when Spark fixes this limitation (maybe in Spark v3.3?), we completely abandon supporting Spark versions that predate it and deprecate sparkHandleInsert?

**Comment by schuemie** [comment]
I'm not quite following. I'm ok with any approach that only requires changes in SqlRender and DatabaseConnector, but I'm opposed to any approach requiring all other packages to modify their SQL code. 

If I understand correctly, the idea is to modify DatabaseConnector::executeSql so it automatically applies this fix to any insert statement?

**Comment by alondhe** [comment]
Correct. In executeSql, I would add something like:

```
  if (inherits(connection, "DatabaseConnectorJdbcConnection") &&
      connection@dbms == "spark") {
    sql <- SqlRender::sparkHandleInsert(sql = sql, connection = connection)
  }
```

So only Spark SQL will process through this function, which splits the sql into separate commands, identifies if any are INSERTs, then uses the live connection to reconstitute the INSERT so as to have the full column list. We are using a similar approach in WebAPI -- passing off SQL commands to sparkHandleInsert() before proceeding with the final execution.

**Review by schuemie — APPROVED** [review]

**Pull request merged**
