### PR TITLE
Adds fix for #188

### PR DESCRIPTION
**Pull request by alondhe**
Adds fix for #188

### CODE REVIEW

**Comment by schuemie** [comment]
I think something went wrong here. You committed directly do develop, and now you have a pull request that basically creates a release? (because it merges develop into master)

**Comment by alondhe** [comment]
> I think something went wrong here. You committed directly do develop, and now you have a pull request that basically creates a release? (because it merges develop into master)

Should I not make a PR, just leave it in the develop branch?

**Comment by schuemie** [comment]
Yes, the idea is you make a pull request to the develop branch ;-)

I'm preparing release now

**Comment by conor-d-mcgrath** [comment]
Should SqlRender be at version 1.6.3 after this merge to master? I see DESCIRPTION file with version 1.6.2 after install.packages("SqlRender").

**Comment by schuemie** [comment]
Yes, we are currently experiencing issues in getting SqlRender into CRAN. Basically, Java in the CRAN test environment is missing for the 32-bit architecture, causing the builds to fail. I notified the CRAN maintainers, but so far no response.

For now I recommend getting the version from github or drat.

**Comment by conor-d-mcgrath** [comment]
Thank you. I built the project from master and copied over contents in existing SqlRender matching existing directories. Maybe the jar would have been enough. I have much cleaner logs in OHDSI Data Quality Dashboard now after a run - just 2 now that are different. Higher pass rate too.

**Pull request merged**
